package char

const (
	SingleQuote        = "'"
	DoubleQuote        = "\""
	Colon              = ":"
	SemiColon          = ";"
	Percent            = "%"
	Underscore         = "_"
	Dot                = "."
	Comma              = ","
	ForwardSlash       = "/"
	BackSlash          = "\\"
	QuestionMark       = "?"
	Asterisk           = "*"
	OpenParenthesis    = "("
	CloseParenthesis   = ")"
	OpenCurlyBracket   = "{"
	CloseCurlyBracket  = "}"
	OpenSquareBracket  = "["
	CLoseSquareBracket = "]"
	Circumflex         = "^"
	Dollars            = "$"
	Dash               = "-"
)
